export const ALL_DOCTOR_REQUEST = "ALL_DOCTOR_REQUEST";
export const ALL_DOCTOR_SUCCESS = "ALL_DOCTOR_SUCCESS";
export const ALL_DOCTOR_FAIL = "ALL_DOCTOR_FAIL";

export const GET_SECHUDLE_REQUEST = "GET_SECHUDLE_REQUEST";
export const GET_SECHUDLE_SUCCESS = "GET_SECHUDLE_SUCCESS";
export const GET_SECHUDLE_FAIL = "GET_SECHUDLE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
