export const RECORD_LIST_REQUEST = "RECORD_LIST_REQUEST";
export const RECORD_LIST_SUCCESS = "RECORD_LIST_SUCCESS";
export const RECORD_LIST_FAIL = "RECORD_LIST_FAIL";

export const RECORD_DETAILS_REQUEST = "RECORD_DETAILS_REQUEST";
export const RECORD_DETAILS_SUCCESS = "RECORD_DETAILS_SUCCESS";
export const RECORD_DETAILS_FAIL = "RECORD_DETAILS_FAIL";

export const NEW_RECORD_REQUEST = "NEW_RECORD_REQUEST";
export const NEW_RECORD_FAIL = "NEW_RECORD_FAIL";

export const UPDATE_RECORD_REQUEST = "UPDATE_RECORD_REQUEST";
export const UPDATE_RECORD_FAIL = "UPDATE_RECORD_FAIL";

export const DELETE_RECORD_REQUEST = "DELETE_RECORD_REQUEST";
export const DELETE_RECORD_FAIL = "DELETE_RECORD_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
