export const CREATE_TICKET_REQUEST = "CREATE_TICKET_REQUEST";
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_FAIL = "CREATE_TICKET_FAIL";

export const GET_ALL_TICKET_REQUEST = "GET_ALL_TICKET_REQUEST";
export const GET_ALL_TICKET_SUCCESS = "GET_ALL_TICKET_SUCCESS";
export const GET_ALL_TICKET_FAIL = "GET_ALL_TICKET_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
