export const ALL_DOCTOR_REQUEST = "ALL_DOCTOR_REQUEST";
export const ALL_DOCTOR_SUCCESS = "ALL_DOCTOR_SUCCESS";
export const ALL_DOCTOR_FAIL = "ALL_DOCTOR_FAIL";

export const GET_SECHUDLE_REQUEST = "GET_SECHUDLE_REQUEST";
export const GET_SECHUDLE_SUCCESS = "GET_SECHUDLE_SUCCESS";
export const GET_SECHUDLE_FAIL = "GET_SECHUDLE_FAIL";

export const ADMIN_CREATE_DOCTOR_REQUEST = "ADMIN_CREATE_DOCTOR_REQUEST";
export const ADMIN_CREATE_DOCTOR_SUCCESS = "ADMIN_CREATE_DOCTOR_SUCCESS";
export const ADMIN_CREATE_DOCTOR_FAIL = "ADMIN_CREATE_DOCTOR_FAIL";

export const ADMIN_EDIT_DOCTOR_REQUEST = "ADMIN_EDIT_DOCTOR_REQUEST";
export const ADMIN_EDIT_DOCTOR_SUCCESS = "ADMIN_EDIT_DOCTOR_SUCCESS";
export const ADMIN_EDIT_DOCTOR_FAIL = "ADMIN_EDIT_DOCTOR_FAIL";

export const ADMIN_DELETE_DOCTOR_REQUEST = "ADMIN_DELETE_DOCTOR_REQUEST";
export const ADMIN_DELETE_DOCTOR_SUCCESS = "ADMIN_DELETE_DOCTOR_SUCCESS";
export const ADMIN_DELETE_DOCTOR_FAIL = "ADMIN_DELETE_DOCTOR_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
