export const CREATE_TICKET_REQUEST = "CREATE_TICKET_REQUEST";
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_FAIL = "CREATE_TICKET_FAIL";

export const GET_ALL_TICKET_REQUEST = "GET_ALL_TICKET_REQUEST";
export const GET_ALL_TICKET_SUCCESS = "GET_ALL_TICKET_SUCCESS";
export const GET_ALL_TICKET_FAIL = "GET_ALL_TICKET_FAIL";

export const ADMIN_GET_ALL_TICKET_REQUEST = "ADMIN_GET_ALL_TICKET_REQUEST";
export const ADMIN_GET_ALL_TICKET_SUCCESS = "ADMIN_GET_ALL_TICKET_SUCCESS";
export const ADMIN_GET_ALL_TICKET_FAIL = "ADMIN_GET_ALL_TICKET_FAIL";

export const ADMIN_STATISTICS_TICKET_REQUEST =
  "ADMIN_STATISTICS_TICKET_REQUEST";
export const ADMIN_STATISTICS_TICKET_SUCCESS =
  "ADMIN_STATISTICS_TICKET_SUCCESS";
export const ADMIN_STATISTICS_TICKET_FAIL = "ADMIN_STATISTICS_TICKET_FAIL";

export const ADMIN_UPDATE_STATUS_TICKET_REQUEST =
  "ADMIN_UPDATE_STATUS_TICKET_REQUEST";
export const ADMIN_UPDATE_STATUS_TICKET_SUCCESS =
  "ADMIN_UPDATE_STATUS_TICKET_SUCCESS";
export const ADMIN_UPDATE_STATUS_TICKET_FAIL =
  "ADMIN_UPDATE_STATUS_TICKET_FAIL";

export const ADMIN_DELETE_TICKET_REQUEST = "ADMIN_DELETE_TICKET_REQUEST";
export const ADMIN_DELETE_TICKET_SUCCESS = "ADMIN_DELETE_TICKET_SUCCESS";
export const ADMIN_DELETE_TICKET_FAIL = "ADMIN_DELETE_TICKET_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
